{% set name = "sagemaker-studio-dataengineering-extensions" %}
{% set version = "1.2.13" %}
{% set python_min = "3.11" %}
{% set sha256 = "9fb2a8d861116d8c773e66744d482b6a01e01156604f7f51bb119e872bf9b0f0" %}
{% set blake2b256 = "fe7a307ad7421b69ecea779ecc4b3585aba6781c206617092386e7436b2e0dbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fe/7a/307ad7421b69ecea779ecc4b3585aba6781c206617092386e7436b2e0dbb/sagemaker_studio_dataengineering_extensions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - jupyterlab >=4.0.0,<5
    - hatchling >=1.5.0
    - nodejs
    - pyzmq
    - jupyter-scheduler >=2.7.0,<3
    - jupyter-packaging ==0.12.3

  run:
    - python >={{ python_min }}
    - pytest
    - jupyterlab >=4.0.0,<5
    - requests
    - schedule
    - boto3
    - jupyter_server >=1.6,<3
    - sagemaker-studio >=1.0.16
    - aws-embedded-metrics
    - async-timeout
    - async-lru
    - pydantic
    - aiobotocore >=2.9,<3
    - jupyter-scheduler >=2.7.0,<3

test:
  imports:
    - sagemaker_data_explorer
    - sagemaker_jupyter_server_extension
    - sagemaker_sparkmonitor
    - sagemaker_ui_doc_manager_jl_plugin
    - sagemaker_ui_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: A python Package to enhance experience of SageMaker Unified Studio
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - yzhum
    - freddylyu173
    - Jas0nch
